apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-at0e
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jhutar-tenant/my-app/devfile-sample-at0e@sha256:8c547674fee1f1349a1a1caab4cd19f121ab781f878f927d3ca9091b183bd39f
        name: my-nodejs
        resources: {}
status: {}
